var comics = {
	0 : {
	  'title' : 'Giang Sơn',
	  'autor' : 'Sa Mac',
	  'source' : 'truyen.hixx.info',
	  'name' : 'localhost',
	  'chapter_id' : 0,
	  'url' : 'http://truyen.hixx.info/truyen/truyen-kiem-hiep/219530/Giang-Son/Chuong-1-Ven-ho-Tay-tu.html',
	  'detail' : 'detail',
	},
	1 : {
	  'title' : 'CHUẾ TẾ ( Ở RỂ )',
	  'autor' : 'Phẫn Nộ Đích Hương Tiêu',
	  'source' : 'truyenyy.com',
	  'name' : 'localhost',
	  'chapter_id' : 0,
	  'url' : 'http://truyenyy.com/doc-truyen/o-re-chue-tue/chuong-1/',
	  'detail' : 'detail',
	},
	2 : {
	  'title' : 'CHUẾ TẾ ( Ở RỂ )',
	  'autor' : 'Phẫn Nộ Đích Hương Tiêu',
	  'source' : 'sstruyen.com',
	  'name' : 'localhost',
	  'chapter_id' : 0,
	  'url' : 'http://sstruyen.com/doc-truyen/lich-su/chue-te--o-re-/q1---chuong-1-o-re-to-gia/670991.html',
	  'detail' : 'detail',
	},
	3 : {
	  'title' : 'Bắc Tống Phong Lưu',
	  'autor' : 'Nam Hi',
	  'source' : 'truyenfull.vn',
	  'name' : 'localhost',
	  'chapter_id' : 53,
	  'url' : 'http://truyenfull.vn/bac-tong-phong-luu/chuong-54/',
	  'detail' : 'detail',
	},
	4 : {
	  'title' : 'Bắc Tống Phong Lưu',
	  'autor' : 'Nam Hi',
	  'source' : 'sstruyen.com',
	  'name' : 'localhost',
	  'chapter_id' : 55,
	  'url' : 'http://sstruyen.com/doc-truyen/tien-hiep/bac-tong-phong-luu/chuong-56-mang-chui-p1/608593.html',
	  'detail' : 'detail',
	},
	5 : {
	  'title' : 'PHONG LƯU',
	  'autor' : 'Ngũ Lang Thúc',
	  'source' : 'truyenyy.com',
	  'name' : 'localhost',
	  'chapter_id' : 0,
	  'url' : 'http://truyenyy.com/doc-truyen/phong-luu/chuong-1/',
	  'detail' : 'detail',
	},
	6 : {
	  'title' : 'PHONG LƯU',
	  'autor' : 'Ngũ Lang Thúc',
	  'source' : 'truyenyy.com',
	  'name' : 'localhost',
	  'chapter_id' : 133,
	  'url' : 'http://truyenyy.com/doc-truyen/phong-luu/chuong-134/',
	  'detail' : 'detail',
	},
	7 : {
	  'title' : 'TRIỆU HOÁN THẦN BINH',
	  'autor' : 'Hạ Nhật Dịch Lãnh',
	  'source' : 'sstruyen.com',
	  'name' : 'localhost',
	  'chapter_id' : 999,
	  'url' : 'http://sstruyen.com/doc-truyen/kiem-hiep/trieu-hoan-than-binh/chuong-996-da-tinh-ty-ty-cung-thich-tim-co/603386.html',
	  'detail' : 'detail',
	},
	8 : {
	  'title' : 'HUYỀN THIÊN',
	  'autor' : 'Ô Sơn',
	  'source' : 'truyenyy.com',
	  'name' : 'localhost',
	  'chapter_id' : 0,
	  'url' : 'http://truyenyy.com/doc-truyen/huyen-thien/chuong-1/',
	  'detail' : 'detail',
	},
	9 : {
	  'title' : 'BẮC TỐNG PHONG LƯU',
	  'autor' : 'Nam Hi',
	  'source' : 'truyenvl.net',
	  'name' : 'localhost',
	  'chapter_id' : 0,
	  'url' : 'http://www.truyenvl.net/bac-tong-phong-luu/chuong-1/',
	  'detail' : 'detail',
	},
	10 : {
	  'title' : 'QUỐC SẮC SINH KIÊU',
	  'autor' : 'Sa Mạc',
	  'source' : 'truyenyy.com',
	  'name' : 'localhost',
	  'chapter_id' : 0,
	  'url' : 'http://truyenyy.com/doc-truyen/quoc-sac-sinh-kieu/chuong-1/',
	  'detail' : 'detail',
	},
	11 : {
	  'title' : 'Đại Địa Chủ Lưu Manh',
	  'autor' : 'Quan Tài Lí Tiếu Thanh',
	  'source' : 'tuchangioi.net',
	  'name' : 'localhost',
	  'chapter_id' : 0,
	  'url' : 'http://tuchangioi.net/dai-dia-chu-luu-manh/chuong-1/',
	  'detail' : 'detail',
	} ,
	12 : {
	  'title' : 'Nạp Thiếp Ký',
	  'autor' : 'Mộc Dật',
	  'source' : 'tuchangioi.net',
	  'name' : 'localhost',
	  'chapter_id' : 0,
	  'url' : 'http://tuchangioi.net/nap-thiep-ky/chuong-1/',
	  'detail' : 'detail',
	},
	13 : {
	  'title' : 'HÌNH DANH SƯ GIA',
	  'autor' : 'Mộc Dật',
	  'source' : 'truyenfull.vn',
	  'name' : 'localhost',
	  'chapter_id' : 0,
	  'url' : 'http://truyenfull.vn/hinh-danh-su-gia/chuong-1/',
	  'detail' : 'detail',
	},
	14 : {
	  'title' : 'GIANG SƠN',
	  'autor' : 'Sa Mạc',
	  'source' : 'truyenfull.vn',
	  'name' : 'localhost',
	  'chapter_id' : 0,
	  'url' : 'http://truyenfull.vn/giang-son/quyen-1-chuong-1/',
	  'detail' : 'detail',
	} ,
	15 : {
	  'title' : 'GIANG SƠN NHƯ THỬ ĐA KIÊU',
	  'autor' : 'Nam Hải Thập Tứ Lang',
	  'source' : 'truyenyy.com',
	  'name' : 'localhost',
	  'chapter_id' : 416,
	  'url' : 'http://truyenyy.com/doc-truyen/giang-son-nhu-thu-da-kieu/chuong-417/',
	  'detail' : 'detail',
	}  
};